services:
  # ----------------------------------------
  # 1. PostgreSQL Database Service
  # ----------------------------------------
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234}
      POSTGRES_DB: ${DB_NAME:-knowledge_hub_db}
    ports:
      - ${DB_PORT_LOCAL:-5433}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # ----------------------------------------
  # 2. Node.js Application Service
  # ----------------------------------------
  # node_app:
  #   build: .
  #   ports:
  #     - ${NODE_PORT}:3000
  #   env_file:
  #     - .env
  #   environment:
  #     NODE_ENV: development
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   command: nodemon app.js

volumes:
  db_data: